name: Initialize Actix Project

on:
  workflow_dispatch:

jobs:
  init-actix-project:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Install cargo-generate
      run: cargo install cargo-generate

    - name: Create Actix project
      run: |
        cargo generate --git https://github.com/actix/actix-template.git --name checkbox-state-machine
        mv checkbox-state-machine/* .
        mv checkbox-state-machine/.gitignore .
        rm -rf checkbox-state-machine

    - name: Update Cargo.toml
      run: |
        sed -i 's/name = "checkbox-state-machine"/name = "${{ github.event.repository.name }}"/' Cargo.toml

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Initialize Actix project" || echo "No changes to commit"
        git push
