name: Initialize Actix Project

on:
  workflow_dispatch:

jobs:
  init-actix-project:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Rust
      uses: actions-rs/toolchain@v4
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install cargo-generate
      run: cargo install cargo-generate

    - name: Create Actix project
      run: |
        cargo generate --git https://github.com/actix/actix-template.git --name my-actix-project
        mv my-actix-project/* .
        mv my-actix-project/.gitignore .
        rm -rf my-actix-project

    - name: Update Cargo.toml
      run: |
        sed -i 's/name = "my-actix-project"/name = "${{ github.event.repository.name }}"/' Cargo.toml

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Initialize Actix project" || echo "No changes to commit"
        git push
